---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./src/*.js"
    - "./tests/**/*.spec.js"
postMerge:
  pattern:
    - "./src/*.js"
    - "./tests/**/*.spec.js"
postRun:
     command:
        - yarn --version
version: 1.0
